<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>StructuredLogViewer.Avalonia</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
    <AvaloniaResource Include="Fonts\*.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.AvaloniaEdit" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StructuredLogger.Utils\StructuredLogger.Utils.csproj" />
    <ProjectReference Include="..\StructuredLogger\StructuredLogger.csproj" />
    <ProjectReference Include="..\StructuredLogViewer.Core\StructuredLogViewer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\StructuredLogViewer\Resources\SolutionFile.xshd" Link="Resources\SolutionFile.xshd" />
  </ItemGroup>

</Project>
